server:
  port: 9001

spring:
  cloud:
    stream:
      default-binder: kafka2
      bindings:
        fizzBuzzProducer-out-0:
          destination: numbers
          binder: kafka1
        process-in-0:
          group: kafka1-consumers
          destination: kafka1topic1
          binder: kafka1
        receive-in-0:
          group: kafka2-consumers
          destination: kafka2topic2
          binder: kafka2
      function:
        definition: process;receive
      binders:
        kafka1:
          type: kafka
          environment:
            spring:
              cloud:
                stream:
                  kafka:
                    binder:
                      brokers: localhost:19092
        kafka2:
          type: kafka
          environment:
            spring:
              cloud:
                stream:
                  kafka:
                    binder:
                      brokers: localhost:9092
                      